Resources:
  AlbCertificate:
    Type: "AWS::CertificateManager::Certificate"
    Properties:
      DomainName: !Join
        - .
        - - !Ref RandomString
          - !Ref HostedZoneName
      DomainValidationOptions:
        - DomainName: !Join
            - .
            - - !Ref RandomString
              - !Ref HostedZoneName
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS
      Tags:
        - Key: Name
          Value: !Sub Certificate-${RandomString}

  Alb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      Scheme: internet-facing
      Subnets:
        - !Ref SubnetIdA
        - !Ref SubnetIdB
      SecurityGroups:
        - !Ref SecurityGroupAlbId
      Tags:
        - Key: Name
          Value: !Sub Alb-${RandomString}

  HttpsTargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      Port: 443
      Protocol: HTTPS
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Sub TargetGroup-HTTPS-${RandomString}

  WsTargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      Port: !Ref ProxyServerPort
      Protocol: HTTPS
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Sub TargetGroup-WS-${RandomString}

  HttpsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn:
      - Alb
      - AlbCertificate
      - HttpsTargetGroup
    Properties:
      Certificates:
        - CertificateArn: !Ref AlbCertificate
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref HttpsTargetGroup
      LoadBalancerArn: !Ref Alb
      Port: 443
      Protocol: HTTPS

  WsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn:
      - Alb
      - AlbCertificate
      - WsTargetGroup
    Properties:
      Certificates:
        - CertificateArn: !Ref AlbCertificate
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref WsTargetGroup
      LoadBalancerArn: !Ref Alb
      Port: !Ref ProxyServerPort
      Protocol: HTTPS

  Route53Record:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Join
        - .
        - - !Ref RandomString
          - !Ref HostedZoneName
      Type: A
      AliasTarget:
        DNSName: !GetAtt Alb.DNSName
        EvaluateTargetHealth: false
        HostedZoneId: !GetAtt Alb.CanonicalHostedZoneID

Parameters:
  VpcId:
    Type: String
    Default: default
    Description: Project Vpc

  HostedZoneName:
    Type: String
    Default: default
    Description: Hosted zone name

  HostedZoneId:
    Type: String
    Default: default
    Description: Hosted zone ID

  SubnetIdA:
    Type: String
    Default: default
    Description: First subnet of ALB

  SubnetIdB:
    Type: String
    Default: default
    Description: Second subnet of ALB

  SecurityGroupAlbId:
    Type: String
    Default: default
    Description: ALB security group

  RandomString:
    Type: String
    Default: default
    Description: Random string used to get unique resources ID if the CF template is launched several times

  ProxyServerPort:
    Type: Number
    Default: 0
    Description: Port used on proxy server
