Resources:
  AlbCertificate:
    Type: "AWS::CertificateManager::Certificate"
    Properties:
      DomainName: !Join
        - .
        - - !Ref RandomString
          - !Ref HostedZoneName
      DomainValidationOptions:
        - DomainName: !Join
            - .
            - - !Ref RandomString
              - !Ref HostedZoneName
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS
      Tags:
        - Key: Name
          Value: !Sub Certificate-${RandomString}

  Alb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub Alb-${RandomString}
      Type: application
      Scheme: internet-facing
      Subnets:
        - !Ref PublicSubnetIdA
        - !Ref PublicSubnetIdB
      SecurityGroups:
        - !Ref SecurityGroupAlbId
      Tags:
        - Key: Name
          Value: !Sub Alb-${RandomString}

  HttpsTargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      Port: 443
      Protocol: HTTPS
      TargetType: ip
      Matcher:
        HttpCode: 404
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Sub TargetGroup-HTTPS-${RandomString}

  WsTargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      Port: !Ref ProxyServerPort
      Protocol: HTTPS
      Matcher:
        HttpCode: 404
      TargetType: ip
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Sub TargetGroup-WS-${RandomString}

  HttpsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn:
      - Alb
      - AlbCertificate
      - HttpsTargetGroup
    Properties:
      Certificates:
        - CertificateArn: !Ref AlbCertificate
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref HttpsTargetGroup
      LoadBalancerArn: !Ref Alb
      Port: 443
      Protocol: HTTPS

  WsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn:
      - Alb
      - AlbCertificate
      - WsTargetGroup
    Properties:
      Certificates:
        - CertificateArn: !Ref AlbCertificate
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref WsTargetGroup
      LoadBalancerArn: !Ref Alb
      Port: !Ref ProxyServerPort
      Protocol: HTTPS

  Route53Record:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Join
        - .
        - - !Ref RandomString
          - !Ref HostedZoneName
      Type: A
      AliasTarget:
        DNSName: !GetAtt Alb.DNSName
        EvaluateTargetHealth: false
        HostedZoneId: !GetAtt Alb.CanonicalHostedZoneID

  Service:
    Type: "AWS::ECS::Service"
    DependsOn:
      - HttpsListener
      - WsListener
    Properties:
      Cluster: !Ref ClusterId
      ServiceName: !Sub GameServer-service-${RandomString}
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref SecurityGroupGameServerTaskId
          Subnets:
            - !Ref PrivateSubnetA
            - !Ref PrivateSubnetB
      DesiredCount: 0
      LaunchType: FARGATE
      TaskDefinition: !Ref TaskDefinitionArn
      HealthCheckGracePeriodSeconds: 300
      LoadBalancers:
        - TargetGroupArn: !Ref HttpsTargetGroup
          ContainerPort: !Ref ProxyServerPort
          ContainerName: !Ref ProxyServerNameContainer
        - TargetGroupArn: !Ref WsTargetGroup
          ContainerPort: !Ref ProxyServerPort
          ContainerName: !Ref ProxyServerNameContainer

  LambdaInvoker:
    DependsOn:
      - Service
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub Call_lambda_when_stack_created_${RandomString}
      Code:
        ZipFile: !Sub |
          import boto3, json
          import cfnresponse

          def lambda_handler(event, context):

            if event['RequestType'] == "Create":

              lambda_client = boto3.client('lambda')
                  
              cfn_event = {
                "game_stacks_table_name": "${GameStacksTableName}",
                "game_stacks_id_column_name": "${GameStacksIdColumnName}",
                "game_stacks_capacity_column_name":"${GameStacksCapacityColumnName}",
                "game_stacks_capacity_value": "${GameStacksCapacityValue}",
                "game_stacks_server_link_column_name": "${GameStacksServerLinkColumnName}",
                "game_stacks_cloud_formation_stack_name_column": "${GameStacksCloudFormationStackNameColumn}",
                "game_stacks_cloud_formation_stack_name_value": "${AWS::StackName}",
                "service_name_column": "${ServiceNameColumn}",
                "service_name_value": "GameServer-service-${RandomString}",
                "game_server_random_string" : "${RandomString}",
                "game_server_hosted_zone_name" : "${HostedZoneName}",
                "is_up_column_name" : "${IsUpColumnName}",
                "game_stacks_is_active_columnn_name" : "${GameStacksIsActiveColumnName}"
              }

              lambda_client.invoke( 
                 FunctionName="${InvokedLambdaFunctionName}",
                 InvocationType='Event',
                 Payload=json.dumps(cfn_event)
              )

            responseData = {}
            cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData, "Primerinvoke")

      Handler: !Sub index.lambda_handler
      Role: !Ref LambdaInvokerRoleArn
      Runtime: python3.9
      Timeout: 5

  Primerinvoke:
    Type: AWS::CloudFormation::CustomResource
    DependsOn: LambdaInvoker
    Version: "1.0"
    Properties:
      ServiceToken: !GetAtt LambdaInvoker.Arn

Parameters:
  VpcId:
    Type: String
    Default: default
    Description: Project Vpc

  HostedZoneName:
    Type: String
    Default: default
    Description: Hosted zone name

  HostedZoneId:
    Type: String
    Default: default
    Description: Hosted zone ID

  PublicSubnetIdA:
    Type: String
    Default: default
    Description: First subnet of ALB

  PublicSubnetIdB:
    Type: String
    Default: default
    Description: Second subnet of ALB

  SecurityGroupAlbId:
    Type: String
    Default: default
    Description: ALB security group

  RandomString:
    Type: String
    Default: default
    Description: Random string used to get unique resources ID if the CF template is launched several times

  ProxyServerPort:
    Type: Number
    Default: 0
    Description: Port used on proxy server

  ProxyServerNameContainer:
    Type: String
    Default: default
    Description: Name of the proxy container

  ClusterId:
    Type: String
    Default: default
    Description: Id of the cluster

  SecurityGroupGameServerTaskId:
    Type: String
    Default: default
    Description: Ecs task security group

  PrivateSubnetA:
    Type: String
    Default: default
    Description: First private subnet of Ecs task

  PrivateSubnetB:
    Type: String
    Default: default
    Description: Second private subnet of Ecs task

  TaskDefinitionArn:
    Type: String
    Default: default
    Description: Arn of the Ecs task definition

  LambdaInvokerRoleArn:
    Type: String
    Default: default
    Description: Arn role for lambda calling another lambda that will update the dynamododb table

  InvokedLambdaFunctionName:
    Type: String
    Default: default
    Description: Name of the function launched by the lambda Invoker

  GameStacksIdColumnName:
    Type: String
    Default: default
    Description: DB ID column name

  GameStacksCapacityColumnName:
    Type: String
    Default: default
    Description: DB Capacity column name

  GameStacksCapacityValue:
    Type: String
    Default: default
    Description: DB Capacity value

  GameStacksServerLinkColumnName:
    Type: String
    Default: default
    Description: DB Link column name

  GameStacksCloudFormationStackNameColumn:
    Type: String
    Default: default
    Description: DB CF stack name column name

  ServiceNameColumn:
    Type: String
    Default: default
    Description: DB Service column name

  IsUpColumnName:
    Type: String
    Default: default
    Description: DB Is Up column name

  GameStacksIsActiveColumnName:
    Type: String
    Default: default
    Description: DB Is Active column name

  GameStacksTableName:
    Type: String
    Default: default
    Description: DB table name
