Resources:

  AlbCertificate:
    Type: "AWS::CertificateManager::Certificate"
    Properties:
      DomainName: !Join
        - .
        - - !Ref RandomString
          - !Ref HostedZoneName
      DomainValidationOptions:
        - DomainName: !Join
            - .
            - - !Ref RandomString
              - !Ref HostedZoneName
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS
      Tags:
        - Key: Name
          Value: !Sub Certificate-${RandomString}
 
 Alb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      Scheme: internet-facing
      Subnets:
        - !Ref SubnetIdA
        - !Ref SubnetIdB
      SecurityGroups:
        - !Ref SecurityGroupAlbId
      Tags:
        - Key: Name
          Value: !Sub Alb-${RandomString}

Parameters:
  VpcId:
    Type: String
    Default: default
    Description: Project Vpc

  HostedZoneName:
    Type: String
    Default: default
    Description: Hosted zone name

  HostedZoneId:
    Type: String
    Default: default
    Description: Hosted zone ID

  SubnetIdA:
    Type: String
    Default: default
    Description: First subnet of ALB

  SubnetIdB:
    Type: String
    Default: default
    Description: Second subnet of ALB

  SecurityGroupAlbId:
    Type: String
    Default: default
    Description: ALB security group

  RandomString:
    Type: String
    Default: default
    Description: Random string used to get unique resources ID if the CF template is launched several times
