name: "deleteResourcesWorkflow"

on:
  workflow_dispatch: {}

jobs:
  deploy:
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_INFRA }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY_INFRA }}
      TF_VAR_deployment_branch: ${{secrets.DEPLOYMENT_BRANCH}}
      TF_VAR_admin_mail: ${{secrets.ADMIN_MAIL}}
      TF_VAR_send_mail: ${{secrets.SEND_MAIL}}
      TF_VAR_proxy_server_tag: ${{ vars.PROXY_SERVER_TAG }}
      TF_VAR_uri_proxy_repo: ${{ secrets.URI_PROXY_REPO }}
      TF_VAR_game_server_tag: ${{ vars.GAME_SERVER_TAG }}
      TF_VAR_uri_game_server_repo: ${{ secrets.URI_GAME_SERVER_REPO }}
      TF_VAR_homepage_repository: ${{secrets.HOMEPAGE_REPOSITORY}}
      TF_VAR_homepage_branch: ${{vars.HOMEPAGE_BRANCH}}
      TF_VAR_homepage_github_token: ${{secrets.HOMEPAGE_GITHUB_TOKEN}}
      TF_VAR_content_server_address: ${{secrets.CONTENT_SERVER_ADDRESS}}
      TF_VAR_game_server_name_container: ${{secrets.GAME_SERVER_NAME_CONTAINER}}
      TF_VAR_proxy_server_name_container: ${{secrets.PROXY_SERVER_NAME_CONTAINER}}
      TF_VAR_app_name: ${{secrets.APP_NAME}}
      TF_VAR_hosted_zone_name: ${{secrets.HOSTED_ZONE_NAME}}
      TF_VAR_subdomain_homepage: ${{secrets.SUBDOMAIN_HOMEPAGE}}
      TF_VAR_subdomain_game_stacks: ${{secrets.SUBDOMAIN_GAME_STACKS}}
      TF_VAR_subdomain_api: ${{secrets.SUBDOMAIN_API}}
      TF_VAR_user_pool_id: ${{secrets.USER_POOL_ID}}
      TF_VAR_user_pool_client_id: ${{secrets.USER_POOL_CLIENT_ID}}
      TF_VAR_identity_pool_id: ${{secrets.IDENTITY_POOL_ID}}
      TF_VAR_user_pool_endpoint: ${{secrets.USER_POOL_ENDPOINT}}

    steps:
      - run: 'echo "ENV: ${{ github.ref_name }}"'
      - name: Checkout code
        uses: actions/checkout@v4
      - run: terraform init -backend-config="access_key=${{ secrets.ACCESS_KEY_STATE }}" -backend-config="secret_key=${{ secrets.SECRET_ACCESS_KEY_STATE }}" -backend-config="bucket=${{ secrets.BUCKET_NAME_STATE }}" -backend-config="key=${{ secrets.KEY_STATE }}" -backend-config="region=eu-west-3"
      - run: terraform destroy -auto-approve
