name: "deleteResourcesWorkflow"

on:
  workflow_dispatch:
    inputs:
      testType:
        description: "Type of tests to run"
        required: true
        default: "integration"

jobs:
  deploy:
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "ENV: ${{ github.ref_name }}"'
      - name: Checkout code
        uses: actions/checkout@v4
      - run: terraform init -backend-config="access_key=${{ secrets.ACCESS_KEY_STATE }}" -backend-config="secret_key=${{ secrets.SECRET_ACCESS_KEY_STATE }}" -backend-config="bucket=${{ secrets.BUCKET_NAME_STATE }}" -backend-config="key=${{ secrets.KEY_STATE }}" -backend-config="region=eu-west-3"
      - run: terraform destroy
